const address_mode = {
    acc: "ACCUMULATOR",
    abs: "ABSOLUTE",
    abx: "ABSOLUTE X",
    aby: "ABSOLUTE Y",
    imm: "IMMEDIATE",
    imp: "IMPLIED",
    ind: "INDIRECT",
    izx: "INDIRECT X",
    izy: "INDIRECT Y",
    rel: "RELATIVE",
    zpo: "ZERO PAGE",
    zpx: "ZERO PAGE X",
    zpy: "ZERO PAGE Y"
}

export const Opcodes = new Map ([
    //0x0x
    [0x00, {instruction : "BRK", address_mode : address_mode.imm, cycles : 7, crosses_page : false}],
    [0x01, {instruction : "ORA", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0x02, undefined],
    [0x03, {instruction : "SLO", address_mode : address_mode.izx, cycles : 8, crosses_page : false}],
    [0x04, {instruction : "NOP", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x05, {instruction : "ORA", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x06, {instruction : "ASL", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x07, {instruction : "SLO", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x08, {instruction : "PHP", address_mode : address_mode.imp, cycles : 3, crosses_page : false}],
    [0x09, {instruction : "ORA", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x0A, {instruction : "ASL", address_mode : address_mode.acc, cycles : 2, crosses_page : false}],
    [0x0B, {instruction : "ANC", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x0C, {instruction : "NOP", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x0D, {instruction : "ORA", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x0E, {instruction : "ASL", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0x0F, {instruction : "SLO", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    //0x1x
    [0x10, {instruction : "BPL", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0x11, {instruction : "ORA", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0x12, undefined],
    [0x13, {instruction : "SLO", address_mode : address_mode.izy, cycles : 8, crosses_page : false}],
    [0x14, {instruction : "NOP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x15, {instruction : "ORA", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x16, {instruction : "ASL", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x17, {instruction : "SLO", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x18, {instruction : "CLC", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x19, {instruction : "ORA", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0x1A, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x1B, {instruction : "SLO", address_mode : address_mode.aby, cycles : 7, crosses_page : false}],
    [0x1C, {instruction : "NOP", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x1D, {instruction : "ORA", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x1E, {instruction : "ASL", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    [0x1F, {instruction : "SLO", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    //0x2x
    [0x20, {instruction : "JSR", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0x21, {instruction : "AND", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0x22, undefined],
    [0x23, {instruction : "RLA", address_mode : address_mode.izx, cycles : 8, crosses_page : false}],
    [0x24, {instruction : "BIT", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x25, {instruction : "AND", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x26, {instruction : "ROL", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x27, {instruction : "RLA", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x28, {instruction : "PLP", address_mode : address_mode.imp, cycles : 4, crosses_page : false}],
    [0x29, {instruction : "AND", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x2A, {instruction : "ROL", address_mode : address_mode.acc, cycles : 2, crosses_page : false}],
    [0x2B, {instruction : "ANC", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x2C, {instruction : "BIT", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x2D, {instruction : "AND", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x2E, {instruction : "ROL", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0x2F, {instruction : "RLA", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    //0x3x
    [0x30, {instruction : "BMI", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0x31, {instruction : "AND", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0x32, undefined],
    [0x33, {instruction : "RLA", address_mode : address_mode.izy, cycles : 8, crosses_page : false}],
    [0x34, {instruction : "NOP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x35, {instruction : "AND", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x36, {instruction : "ROL", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x37, {instruction : "RLA", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x38, {instruction : "SEC", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x39, {instruction : "AND", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0x3A, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x3B, {instruction : "RLA", address_mode : address_mode.aby, cycles : 7, crosses_page : false}],
    [0x3C, {instruction : "NOP", address_mode : address_mode.abx, cycles : 4, crosses_page : false}],
    [0x3D, {instruction : "AND", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x3E, {instruction : "ROL", address_mode : address_mode.abx, cycles : 7, crosses_page : true}],
    [0x3F, {instruction : "RLA", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    //0x4x
    [0x40, {instruction : "RTI", address_mode : address_mode.imp, cycles : 6, crosses_page : false}],
    [0x41, {instruction : "EOR", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0x42, undefined],
    [0x43, {instruction : "SRE", address_mode : address_mode.izx, cycles : 8, crosses_page : false}],
    [0x44, {instruction : "NOP", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x45, {instruction : "EOR", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x46, {instruction : "LSR", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x47, {instruction : "SRE", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x48, {instruction : "PHA", address_mode : address_mode.imp, cycles : 3, crosses_page : false}],
    [0x49, {instruction : "EOR", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x4A, {instruction : "LSR", address_mode : address_mode.acc, cycles : 2, crosses_page : false}],
    [0x4B, {instruction : "ALR", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x4C, {instruction : "JMP", address_mode : address_mode.abs, cycles : 3, crosses_page : false}],
    [0x4D, {instruction : "EOR", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x4E, {instruction : "LSR", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0x4F, {instruction : "SRE", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    //0x5x
    [0x50, {instruction : "BVC", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0x51, {instruction : "EOR", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0x52, undefined],
    [0x53, {instruction : "SRE", address_mode : address_mode.izy, cycles : 8, crosses_page : false}],
    [0x54, {instruction : "NOP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x55, {instruction : "EOR", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x56, {instruction : "LSR", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x57, {instruction : "SRE", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x58, {instruction : "CLI", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x59, {instruction : "EOR", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0x5A, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x5B, {instruction : "SRE", address_mode : address_mode.aby, cycles : 7, crosses_page : false}],
    [0x5C, {instruction : "NOP", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x5D, {instruction : "EOR", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x5E, {instruction : "LSR", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    [0x5F, {instruction : "SRE", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    //0x6x
    [0x60, {instruction : "RTS", address_mode : address_mode.imp, cycles : 6, crosses_page : false}],
    [0x61, {instruction : "ADC", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0x62, undefined],
    [0x63, {instruction : "RRA", address_mode : address_mode.izx, cycles : 8, crosses_page : false}],
    [0x64, {instruction : "NOP", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x65, {instruction : "ADC", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x66, {instruction : "ROR", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x67, {instruction : "RRA", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0x68, {instruction : "PLA", address_mode : address_mode.imp, cycles : 4, crosses_page : false}],
    [0x69, {instruction : "ADC", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x6A, {instruction : "ROR", address_mode : address_mode.acc, cycles : 2, crosses_page : false}],
    [0x6B, {instruction : "ARR", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x6C, {instruction : "JMP", address_mode : address_mode.ind, cycles : 5, crosses_page : false}],
    [0x6D, {instruction : "ADC", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x6E, {instruction : "ROR", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0x6F, {instruction : "RRA", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    //0x7x
    [0x70, {instruction : "BVS", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0x71, {instruction : "ADC", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0x72, undefined],
    [0x73, {instruction : "RRA", address_mode : address_mode.izy, cycles : 8, crosses_page : false}],
    [0x74, {instruction : "NOP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x75, {instruction : "ADC", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x76, {instruction : "ROR", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x77, {instruction : "RRA", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0x78, {instruction : "SEI", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x79, {instruction : "ADC", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0x7A, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x7B, {instruction : "RRA", address_mode : address_mode.aby, cycles : 7, crosses_page : false}],
    [0x7C, {instruction : "NOP", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x7D, {instruction : "ADC", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0x7E, {instruction : "ROR", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    [0x7F, {instruction : "RRA", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    //0x8x
    [0x80, {instruction : "NOP", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x81, {instruction : "STA", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0x82, {instruction : "NOP", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x83, {instruction : "SAX", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0x84, {instruction : "STY", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x85, {instruction : "STA", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x86, {instruction : "STX", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x87, {instruction : "SAX", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0x88, {instruction : "DEY", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x89, {instruction : "NOP", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x8A, {instruction : "TXA", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x8B, {instruction : "XAA", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0x8C, {instruction : "STY", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x8D, {instruction : "STA", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x8E, {instruction : "STX", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0x8F, {instruction : "SAX", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    //0x9x
    [0x90, {instruction : "BCC", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0x91, {instruction : "STA", address_mode : address_mode.izy, cycles : 6, crosses_page : false}],
    [0x92, undefined],
    [0x93, {instruction : "AHX", address_mode : address_mode.izy, cycles : 6, crosses_page : false}],
    [0x94, {instruction : "STY", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x95, {instruction : "STA", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0x96, {instruction : "STX", address_mode : address_mode.zpy, cycles : 4, crosses_page : false}],
    [0x97, {instruction : "SAX", address_mode : address_mode.zpy, cycles : 4, crosses_page : false}],
    [0x98, {instruction : "TYA", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x99, {instruction : "STA", address_mode : address_mode.aby, cycles : 5, crosses_page : false}],
    [0x9A, {instruction : "TXS", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0x9B, {instruction : "TAS", address_mode : address_mode.aby, cycles : 5, crosses_page : false}],
    [0x9C, {instruction : "SHY", address_mode : address_mode.abx, cycles : 5, crosses_page : false}],
    [0x9D, {instruction : "STA", address_mode : address_mode.abx, cycles : 5, crosses_page : false}],
    [0x9E, {instruction : "SHX", address_mode : address_mode.aby, cycles : 5, crosses_page : false}],
    [0x9F, {instruction : "AHX", address_mode : address_mode.aby, cycles : 5, crosses_page : false}],
    //0xAx
    [0xA0, {instruction : "LDY", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xA1, {instruction : "LDA", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0xA2, {instruction : "LDX", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xA3, {instruction : "LAX", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0xA4, {instruction : "LDY", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xA5, {instruction : "LDA", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xA6, {instruction : "LDX", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xA7, {instruction : "LAX", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xA8, {instruction : "TAY", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xA9, {instruction : "LDA", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xAA, {instruction : "TAX", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xAB, {instruction : "LAX", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xAC, {instruction : "LDY", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xAD, {instruction : "LDA", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xAE, {instruction : "LDX", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xAF, {instruction : "LAX", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    //0xBx
    [0xB0, {instruction : "BCS", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0xB1, {instruction : "LDA", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0xB2, undefined],
    [0xB3, {instruction : "LAX", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0xB4, {instruction : "LDY", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0xB5, {instruction : "LDA", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0xB6, {instruction : "LDX", address_mode : address_mode.zpy, cycles : 4, crosses_page : false}],
    [0xB7, {instruction : "LAX", address_mode : address_mode.zpy, cycles : 4, crosses_page : false}],
    [0xB8, {instruction : "CLV", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xB9, {instruction : "LDA", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0xBA, {instruction : "TSX", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xBB, {instruction : "LAS", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0xBC, {instruction : "LDY", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0xBD, {instruction : "LDA", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0xBE, {instruction : "LDX", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0xBF, {instruction : "LAX", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    //0xCx
    [0xC0, {instruction : "CPY", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xC1, {instruction : "CMP", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0xC2, {instruction : "NOP", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xC3, {instruction : "DCP", address_mode : address_mode.izx, cycles : 8, crosses_page : false}],
    [0xC4, {instruction : "CPY", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xC5, {instruction : "CMP", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xC6, {instruction : "DEC", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0xC7, {instruction : "DCP", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0xC8, {instruction : "INY", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xC9, {instruction : "CMP", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xCA, {instruction : "DEX", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xCB, {instruction : "AXS", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xCC, {instruction : "CPY", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xCD, {instruction : "CMP", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xCE, {instruction : "DEC", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0xCF, {instruction : "DCP", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    //0xDx
    [0xD0, {instruction : "BNE", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0xD1, {instruction : "CMP", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0xD2, undefined],
    [0xD3, {instruction : "DCP", address_mode : address_mode.izy, cycles : 8, crosses_page : false}],
    [0xD4, {instruction : "NOP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0xD5, {instruction : "CMP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0xD6, {instruction : "DEC", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0xD7, {instruction : "DCP", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0xD8, {instruction : "CLD", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xD9, {instruction : "CMP", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0xDA, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xDB, {instruction : "DCP", address_mode : address_mode.aby, cycles : 7, crosses_page : false}],
    [0xDC, {instruction : "NOP", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0xDD, {instruction : "CMP", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0xDE, {instruction : "DEC", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    [0xDF, {instruction : "DCP", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    //0xEx
    [0xE0, {instruction : "CPX", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xE1, {instruction : "SBC", address_mode : address_mode.izx, cycles : 6, crosses_page : false}],
    [0xE2, {instruction : "NOP", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xE3, {instruction : "ISC", address_mode : address_mode.izx, cycles : 8, crosses_page : false}],
    [0xE4, {instruction : "CPX", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xE5, {instruction : "SBC", address_mode : address_mode.zpo, cycles : 3, crosses_page : false}],
    [0xE6, {instruction : "INC", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0xE7, {instruction : "ISC", address_mode : address_mode.zpo, cycles : 5, crosses_page : false}],
    [0xE8, {instruction : "INX", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xE9, {instruction : "SBC", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xEA, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xEB, {instruction : "SBC", address_mode : address_mode.imm, cycles : 2, crosses_page : false}],
    [0xEC, {instruction : "CPX", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xED, {instruction : "SBC", address_mode : address_mode.abs, cycles : 4, crosses_page : false}],
    [0xEE, {instruction : "INC", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    [0xEF, {instruction : "ISC", address_mode : address_mode.abs, cycles : 6, crosses_page : false}],
    //0xFx
    [0xF0, {instruction : "BEQ", address_mode : address_mode.rel, cycles : 2, crosses_page : true}],
    [0xF1, {instruction : "SBC", address_mode : address_mode.izy, cycles : 5, crosses_page : true}],
    [0xF2, undefined],
    [0xF3, {instruction : "ISC", address_mode : address_mode.izy, cycles : 8, crosses_page : false}],
    [0xF4, {instruction : "NOP", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0xF5, {instruction : "SBC", address_mode : address_mode.zpx, cycles : 4, crosses_page : false}],
    [0xF6, {instruction : "INC", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0xF7, {instruction : "ISC", address_mode : address_mode.zpx, cycles : 6, crosses_page : false}],
    [0xF8, {instruction : "SED", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xF9, {instruction : "SBC", address_mode : address_mode.aby, cycles : 4, crosses_page : true}],
    [0xFA, {instruction : "NOP", address_mode : address_mode.imp, cycles : 2, crosses_page : false}],
    [0xFB, {instruction : "ISC", address_mode : address_mode.aby, cycles : 7, crosses_page : false}],
    [0xFC, {instruction : "NOP", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0xFD, {instruction : "SBC", address_mode : address_mode.abx, cycles : 4, crosses_page : true}],
    [0xFE, {instruction : "INC", address_mode : address_mode.abx, cycles : 7, crosses_page : false}],
    [0xFF, {instruction : "ISC", address_mode : address_mode.abx, cycles : 7, crosses_page : false}]
])